---
- hosts: all
  become: true
  gather_facts: false
  tasks:

# Jenkins
  - name: Download Jenkins Repo 
    apt_key:
      url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
      state: present
    when: inventory_hostname in groups['jenkins']

  - name: ensure the repo is configured    
    apt_repository: repo='deb https://pkg.jenkins.io/debian-stable binary/' state=present
    when: inventory_hostname in groups['jenkins']

  - name: undate apt cache
    apt:
      update_cache: yes
      state: latest
    when: inventory_hostname in groups['jenkins']

  - name: install java
    apt:
      name: openjdk-11-jdk
      state: present
    when: inventory_hostname in groups['jenkins']
     
  - name: install jenkins
    apt:
      name: jenkins
      state: latest
    when: inventory_hostname in groups['jenkins']

  - name: start jenkins
    service:
      name: jenkins
      enabled: true
      state: started
    when: inventory_hostname in groups['jenkins']

# Docker
  - name: Docker - Install required system packages
    apt:
      pkg:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - python3-pip
        - virtualenv
        - python3-setuptools
      state: latest
      update_cache: true    

  - name: Docker - Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Docker - Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
      state: present

  - name: Docker - Deb - Update apt and install docker-ce
    apt:
      name: docker-ce
      state: latest
      update_cache: true

  - name: Docker - Start Docker service
    service:
      name: docker
      state: started
      enabled: yes

  - name: Make docker group
    group: 
      name: docker
      state: present

  - name: Add support to docker group
    user:
      name: support
      groups: docker
      append: yes

  - name: Add jenkins to docker group
    user:
      name: jenkins
      groups: docker
      append: yes
    when: inventory_hostname in groups['jenkins']

      

